import { Rank } from "./permissions.ts";

export interface User {
  id: string; // Phone number
  phoneNumber: string;
  name: string;
  rank: Rank;
  premiumExpiry?: Date;
}

export interface Chat {
  id: string;
  name: string;
  isGroup: boolean;
  isActive: boolean; // Is bot enabled in this group?
}

export interface Message {
  id: string;
  remoteId: string; // Generated by WhatsApp
  body: string;
  timestamp: number;
  from: User;
  chat: Chat;
  hasMedia: boolean;
  mediaType?: "image" | "video" | "audio" | "document" | "sticker";
}
