export const CONFIG_KEYS = {
  COMMAND_PREFIX: "COMMAND_PREFIX",
  ADMIN_COMMAND_PREFIX: "ADMIN_COMMAND_PREFIX",
  ROBOT_EMOJI: "ROBOT_EMOJI",
  TEMP_DIR: "TEMP_DIR",
  MAX_USER_MSG_LENGTH: "MAX_USER_MSG_LENGTH",
  MAX_TOKENS: "MAX_TOKENS",
  MAX_CONVERSATION_LENGTH: "MAX_CONVERSATION_LENGTH",
};

export default {
  CONFIG_KEYS,
  [CONFIG_KEYS.ROBOT_EMOJI]: "🤖",
  [CONFIG_KEYS.TEMP_DIR]: "./media",
};
