name: 👷 CI/CD (Bun)

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: jdx/mise-action@v2

      - run: bun install --frozen-lockfile
      - run: bunx oxfmt --check .
      - run: mise run check
